

COHORT_INTENT = "cohort"
ENROLLMENT_INTENT = "enrollment"
ADMISSION_INTENT = "admission"
FRESHMAN_PROFILE_INTENT = "freshman_profile"
HIGH_SCHOOL_UNITS_INTENT = "high_school_units"
BASIS_FOR_SELECTION_INTENT = "basis_for_selection"
TRANSFER_ADMISSION_INTENT = "transfer_admission"
STUDENT_LIFE_INTENT = "student_life"



COHORT_BY_YEAR_ENTITY_LABEL = "cohort_by_year"
STUDENT_ENROLLMENT_RESULT_ENTITY_LABEL = "student_enrollment_result"
YEAR_ENTITY_LABEL = "year"


INITIAL_COHORT_ENTITY_LABEL = "initial_final"
# FINAL_COHORT_ENTITY_LABEL = 'initial_final'
EXEMPTION_ENTITY_LABEL = "exemptions"
AGGREGATION_ENTTIY_LABEL = "aggregation"
NUMBER_ENTITY_LABEL = "number"


AID_ENTITY_LABEL = "aid_status"
RECIPIENT_OF_PELL_GRANT_ENTITY_LABEL = "pell"
RECIPIENT_OF_STAFFORD_LOAN_NO_PELL_GRANT_ENTITY_LABEL = "stafford"
NO_AID_ENTITY_LABEL = "no-aid"

YEAR_FOR_COLLEGE_ENTITY_LABEL = "years_for_college"

RANGE_ENTITY_LABEL  = "range"

MONGO_DB_CONNECTION_STRING = "mongodb://localhost:27017"

DEFINITION= "definition"
DATABASE_PRENAME = "CDS_"
CDS_DATABASE_NAME_TEMPLATE = DATABASE_PRENAME +"{start_year}_{end_year}"
CDS_DEFINITION_DATABASE_NAME = DATABASE_PRENAME + DEFINITION


DATABASE_SPARSE_MATRIX_ROWS_KEY = "rows"
DATABASE_SPARSE_MATRIX_SUBSECTION_KEY = "subsection"
QUESTION_COLUMN_KEY = "question"

DATABASE_SUBSECTION_FIELD_KEY = "subsection"
DATABASE_METADATA_FIELD_KEY = "metadata"
DATABASE_QUESTION_ANSWERS_KEY = "questionAnswers"

#REGEX pattern to match annual data.
ANNUAL_DATA_REGEX_PATTERN = ".+_\d+_\d+"
#Regex pattern to match definite data
DEFINITION_DATA_REGEX_PATTERN = ".+"+DEFINITION
