DB_UNANSWERED_QUESTION_DATE_FIELD_KEY = "post_date"
DB_UNANSWERED_QUESTION_ANSWER_FIELD_KEY = "answer"
DB_UNANSWERED_QUESTION_QUESTION_FIELD_KEY = "content"
DB_UNANSWERED_QUESTION_IS_ADDRESSED_FIELD_KEY = "is_addressed"