name: Integration Test Workflow

on: [push]

#Define a job
jobs:

  integration-test:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      matrix:
        python-version: ["3.8"]
        mongodb-version: ['6.0']
        

    # Define steps for the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install rasa==3.2.8
          pip install farm-haystack
          pip install "tensorflow>=2.0.0"
          pip install --upgrade tensorflow-hub
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install "numpy>=1.22.0,<1.24.0"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Start Rasa Server
        run: python -m rasa run --cors "*" --enable-api &
        
      - name: Wait for Rasa Server
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http://localhost:5005

      - name: Test knowledgebase
        run: python -m unittest tests/test_integrationKnowledgebaseAndDataSource.py
      - name: Upload unit test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

    


  