name: Integration Test Workflow

on: [push]

#Define a job
jobs:

  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    # Define steps for the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install rasa==3.2.10
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Start Rasa Server
        run: python -m rasa run --cors "*" --enable-api

      - name: Test knowledgebase
        run: python -m unittest tests/test_integrationKnowledgebaseAndDataSource.py
      - name: Upload unit test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

    


  